### ISSUE TITLE
Support for Firebase Queries

### ISSUE THREAD

**Issue by deldrid1** [electricimp/Firebase#2]
Are there any plans to update this library to support [Streaming Rest Queries](https://www.firebase.com/docs/rest/guide/retrieving-data.html#section-rest-queries) and [filtering data](https://www.firebase.com/docs/rest/guide/retrieving-data.html#section-rest-filtering)?  

I think it would be fairly straight forward to implement, just wanted to check to see if anyone was working on it before I got my hands dirty :) 

Along the same lines, I would also like to have a function that would provide an array of the properly ordered/sorted keys as laid out at https://www.firebase.com/docs/rest/guide/retrieving-data.html#section-rest-ordered-data

**Comment by betzrhodes** [comment]
These are definitely things we would be interested in adding, however no one is currently working on this.  If you do implement any of these features please submit a pull request.

**Comment by blindman2k** [comment]
@deldrid1, your changes have been added and the library is now at v1.1.0. Thanks.

**Comment by myurasov** [comment]
Due to no guarantees from Squirrel on traversing order on objects, `orderBy` has limited use, since we're providing data in decoded (ie table) form which doesn't preserve the order of keys in FB response (see #9).
