### ISSUE TITLE
Unexpected JSON parse errors on reading the stream of events

### ISSUE THREAD

**Issue by ppetrosh** [electricimp/Firebase#20]
The issue is that from time to time an exception is thrown:

[Agent]	ERROR: Exception while decoding (0 bytes): 
[Agent]	ERROR: Invalid JSON (line 428) 
[Agent]	ERROR: in _parseEventMessage agent_code:431 
[Agent]	ERROR: from unknown agent_code:342

The problem is with reading events of "text/event-stream" type from the stream. And it's base on our assumption that they arrive as full and complete blocks of messages:

```
event: <event name>
data: <JSON encoded data payload>
```

However what happens (and I'm not sure if it violates a spec) is that the message is split into two:

```
event: <event name>
data:
```
arrives as one message and
```
<JSON encoded data payload>
```
follows it separately.

Which we crashes our parser.

Not sure if they can split it into more parts. But I wouldn't assume they will never do so. So we just need to handle this case.

**Comment by terrencebarr** [comment]
Looks like our parser just needs to be made more robust to support these split message scenariois

**Comment by ppetrosh** [comment]
In fact split message issue is not that easy as it may seem to be as events arrive in different formats and we may end up implementing parser for https://www.w3.org/TR/eventsource/#parsing-an-event-stream. But for this particular use case I'll probably try a simple local fix for now (for the sake of performance and footprint). I tested it on various scenarios and it seems to work well so far.

But if we hit this issue in the future with a different pattern, I'd consider a proper parser/validator to be implemented.

**Comment by ppetrosh** [comment]
Also the split message issue is not the only potential cause of the JSON parser error that we have with the library. There is another problem with processing responses from the Firebase (for example in case of too frequent requests). We assume that any response that we get is a valid JSON which is not the case. I could reproduce this issue as well.

This one is going to be fixed with the same PR.

**Comment by terrencebarr** [comment]
Sounds like we should also file a bug with Firebase

**Comment by ppetrosh** [comment]
Oh I should have mentioned this: response body is not a valid JSON document as it's empty in case of some errors (439 for example). But that's a valid error response as all the necessary information is returned in the headers and the status code which speaks for itself. So I don't think it's a Firebase issue, it's our assumption that's incorrect.

**Comment by ppetrosh** [comment]
Fixed in https://github.com/electricimp/Firebase/pull/21
