### ISSUE TITLE
Error on line 328

### ISSUE THREAD

**Issue by jamesgough** [electricimp/Firebase#28]
I think there is an error on line 328, should the last check be resp.statuscode == 503
not res.statuscode == 503
line 328  } else if (resp.statuscode == 28 || resp.statuscode == 429 || res.statuscode == 503) {

**Comment by betzrhodes** [comment]
Yes. Thanks for catching this. Just opened a pull request with this fix. https://github.com/electricimp/Firebase/pull/29
