### ISSUE TITLE
Firebase Authentication: Mandatory? Upgrade by Tuesday, December 18th, 2018

### ISSUE THREAD

**Issue by deldrid1** [electricimp/Firebase#31]
See https://docs.google.com/document/d/1vpQV8DBQLkIZci7Vh8N4LUHyTkBOsuW5eXE1x8IAqvw/preview#heading=h.nh3bjpr71p53

It's not 100% clear, but I suspect that  the authentication mechanism used by this library may  stop working on Tuesday, December 18th, 2018.

https://firebase.google.com/docs/database/rest/auth has documentation on how authentication should be implemented now.

**Comment by ppetrosh** [comment]
Thank you, @deldrid1 for heads up! We'll update the auth mechanism, we have a task for this already.

**Comment by ppetrosh** [comment]
@deldrid1 can you please make sure https://github.com/electricimp/Firebase/pull/34 works for you before I go ahead and publish the changes.

**Comment by betzrhodes** [comment]
fixed in release https://github.com/electricimp/Firebase/releases/tag/v3.2.0
