### ISSUE TITLE
Incorrect Callback behaviour during PUT Request

### ISSUE THREAD

**Issue by alistairsmarter** [electricimp/Firebase#5]
In my sample code, I have two callbacks as follows:
`_firebase.on( "/settings", _deviceSettingsUpdate.bindenv(this) );
_firebase.on( "/commands", _deviceCommandsUpdate.bindenv(this) );`

When first opening a stream, all data, including from the /settings node, heads to just the _deviceCommandsUpdate callback. I suspect this is happening around line 366 as part of a PUT request.

I understand there may be a wish/intention to show root nodes during a PUT/DELETE but if so, this is having a more undesirable effect.

**Comment by betzrhodes** [comment]
Great find.  This is now fixed in v1.1.1
