### ISSUE TITLE
Could not parse auth token.

### ISSUE THREAD

**Issue by deldrid1** [electricimp/Firebase#8]
Happens on Firebase.once Shallow query

**Comment by blindman2k** [comment]
Hi @deldrid1, can you give us a bit more information on what the error is and how to reproduce it?

**Comment by deldrid1** [comment]
Sorry - I was clearly in a rush and I filed this on the wrong repo. It was supposed to go on https://github.com/deldrid1/node-red-contrib-firebase.

**Comment by blindman2k** [comment]
Best bug report ever :)
